### ISSUE TITLE
Am I forced to use path-to-regexp if I want to pass parameter to my endpoint?

### ISSUE THREAD

**Issue by vegidio** [instantcommerce/next-api-decorators#475]
Hi,

I'm trying to have two different endpoints in my Next.js project, following the file structure below:

The first endpoint is `/pages/api/countries/index.ts` (this will return a list of countries)

```typescript
class Handler {
    @Get()
    findAll(): Promise<Country[]> {
        return ... // code to return a list of countries
    }
}

export default createHandler(Handler);
```

The second endpoint is `/pages/api/countries/[code].ts` (this returns one country that matches the `code` param)

```typescript
class Handler {
    @Get()
    findOne(@Param('code') code: string): Promise<Country> {
        return ... // code to return one country
    }
}

export default createHandler(Handler);
```

With the setup above, and **without** `path-to-regexp` installed, this is what happens:

1. If I send a request `GET /api/countries` then I successfully get the list of countries ✅
2. If I send a request `GET /api/countries/bra` (where `bra` is the country code) then the method `findOne(@Param('code') code: string): Promise<Country>` is called in my second file, however the parameter `code` is `undefined`. ❌

I tried to use many variations of `@Get()` in the second endpoint like `@Get('code')`, `@Get(':code')` and `@Get('/:code')` but nothing seems to work.

Is there a way to pass parameters to the second endpoint **without** having to use `path-to-regexp`.

Thanks for the great package, btw.

**Comment by Josyto** [comment]
Hi @vegidio, is a bit tricky, as getting dynamic parameters depends on whether you install the `path-to-regexp` dependency or not.

Example without `path-to-regex`. You must use `Query` instead of `Param` to get dynamic path values or query params, they are indistinguishable. 

```js
// /pages/api/countries/[code].ts
// Tested by http://localhost:3000/api/countries/dsa?name=John
import { createHandler, Get, Query } from "next-api-decorators";

class Handler {
  @Get()
  findOne(@Query("code") code: string, @Query("name") name: string) {
    return { code, name };
  }
}

export default createHandler(Handler);
```

Example with `path-to-regex`. You must respect the Next folder structure or do it as indicated in the [documentation](https://next-api-decorators.vercel.app/docs/routing/route-matching) (one class multiple functions with [[...params]]).
However, whichever way you do it, if you install the dependency, **it forces you** to put inside the method decorator the subpath in this way.

This way the @Param decorator is for routes and the @Query decorator is for query params. 

```js
// /pages/api/countries/[code].ts
// Tested by http://localhost:3000/api/countries/dsa?name=John
import { createHandler, Get, Param, Query } from "next-api-decorators";

class Handler {
  @Get("/:code")
  findOne(@Param("code") code: string, @Query("name") name: string) {
    return { code, name };
  }
}

export default createHandler(Handler);

```

As a suggestion I think a good improvement would be that the library doesn't change its behaviour just because you install path-to-regexp, instead it would depend on whether you put something in the method decorator or not, which would be simpler.

The problem with the @Param and @Query decorators comes from Next as it mixes the concepts of param and query in the NextApiRequest class.

I hope it helps you

**Comment by vegidio** [comment]
@Josyto Thank you very much for your help! 😃 Using `@Query` instead of `@Param` solved the problem, even though it looked a little counter intuitive.

And I agree with you on this suggestion:

> As a suggestion I think a good improvement would be that the library doesn't change its behaviour just because you install path-to-regexp, instead it would depend on whether you put something in the method decorator or not, which would be simpler.

I think it would make more sense of the package behaved like this.
